--   目标数据库:	mpi
--   脚本生成时间:	12-5月 -2016   09:09
ALTER TABLE "MPI"."BASE_USER" MOVE TABLESPACE "MPI2" 
ALTER INDEX "MPI"."PK_BASE_USER" REBUILD TABLESPACE "MPI2" 
ALTER TABLESPACE "MPI" COALESCE
ALTER TABLE "MPI"."BASE_USER" MOVE TABLESPACE "MPI" 
ALTER INDEX "MPI"."PK_BASE_USER" REBUILD TABLESPACE "MPI" 
BEGIN DBMS_STATS.GATHER_TABLE_STATS('"MPI"', '"BASE_USER"', estimate_percent=>NULL, cascade=>TRUE); END;